### ISSUE TITLE
한송두송 프로젝트

### ISSUE THREAD

**Issue by mvcweb75** [mvcweb75/study#4]
SAAF 캐릭터 만들기 대회 출전 대비책 및 준비 공동 프로젝트

**Comment by mvcweb75** [comment]
이번 캐릭터는 어떤걸로 할 생각이니?

**Comment by mvcweb75** [comment]
캐릭터는 어떤 걸로 할 생각이니?

**Comment by ankyungmin729** [comment]
별채탈 떡다리탈 중 하나로 선택해서 할 생각입니다.

**Comment by mvcweb75** [comment]
그럼 별채탈이 괜찮은것 같은데... 한번 텍스트 파일에 그 설명을 써서 올려볼래?

**Comment by ankyungmin729** [comment]
네넨
